name: Build and Serve Production Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Install serve (static server)
        run: npm install -g serve

      - name: Start production server
        run: |
          serve -s dist -l 8080 &
          echo $! > app.pid
          sleep 10

      - name: Check application
        run: |
          curl --silent --fail http://localhost:8080 || (kill $(cat app.pid) && exit 1)

      - name: Stop production server
        run: |
          kill $(cat app.pid)
          rm -f app.pid
